---
- name: Check Tucny repo file
  stat:
    path: /etc/yum.repos.d/tucny-asterisk.repo
  register: tucny_asterisk_repo

- name: Install Tucny repo
  get_url:
    url: https://ast.tucny.com/repo/tucny-asterisk.repo
    dest: /etc/yum.repos.d/tucny-asterisk.repo
  when: not tucny_asterisk_repo.stat.exists

- name: Import Tucny GPG key
  rpm_key:
    key: https://ast.tucny.com/repo/RPM-GPG-KEY-dtucny
    state: present

- name: Enable asterisk repo
  ini_file:
    path: /etc/yum.repos.d/tucny-asterisk.repo
    section: "{{ item }}"
    option: enabled
    value: 1
    no_extra_spaces: yes
  with_items:
    - asterisk-13
    - asterisk-common

- name: Install packages
  yum:
    name: [ 
      'asterisk',
      'asterisk-sip',
      'asterisk-mysql',
      'asterisk-odbc',
      'asterisk-mp3',
      'asterisk-iax2',
      'asterisk-sounds-core-en',
      'asterisk-sounds-core-en-wav',
    ]
    state: present
    disable_gpg_check: yes

- name: Enable service asterisk and ensure it is not masked
  systemd:
    name: asterisk
    state: started
    enabled: yes
    masked: no

