---
- name: Disable selinux
  selinux:
    state: disabled

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Check Tucny repo file
  stat:
    path: /etc/yum.repos.d/tucny-asterisk.repo
  register: tucny_asterisk_repo

- name: Install Tucny repo
  get_url:
    url: https://ast.tucny.com/repo/tucny-asterisk.repo
    dest: /etc/yum.repos.d/tucny-asterisk.repo
  when: not tucny_asterisk_repo.stat.exists

- name: Import Tucny GPG key
  rpm_key:
    key: https://ast.tucny.com/repo/RPM-GPG-KEY-dtucny
    state: present

- name: Enable asterisk repo
  ini_file:
    path: /etc/yum.repos.d/tucny-asterisk.repo
    section: asterisk-13
    option: enabled
    value: 1
    no_extra_spaces: yes

- name: Install packages
  yum:
    name: [ 
      'asterisk',
      'asterisk-sip',
      'asterisk-mysql',
      'asterisk-mp3',
      'asterisk-iax2',
    ]
    state: present
    disable_gpg_check: yes

- name: Enable service asterisk and ensure it is not masked
  systemd:
    name: asterisk
    state: started
    enabled: yes
    masked: no

- include_tasks: common.yml
#- include_tasks: sip_conf.yml
- include_tasks: sngrep.yml
- include_tasks: firewall.yml
- include_tasks: ntp.yml
