- name: add sip template
  blockinfile:
    path: /etc/asterisk/sip.conf
    block: |
      [local-phone](!)                        ; a template
              type=friend
              host=dynamic
              context=ael-internal
              qualify=yes
              callwaiting=no
              callcounter=yes
              threewaycalling=yes
              transfer=yes
              canpark=yes
              callgroup=1
              pickupgroup=1
              secret=CHANGEME
              nat=force_rport,comedia
              canreinvite=no
              dtmfmode=rfc2833
              disallow=all
              allow=alaw
              allow=ulaw
              t38pt_udptl=yes
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
  notify: sip reload

- name: add sip template
  blockinfile:
    path: /etc/asterisk/sip.conf
    block: |
      [{{ item.name }}](local-phone)
              callerid=<{{ item.callerid }}>
              accountcode={{ item.name }}
              defaultuser={{ item.name }}
    marker: "; {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: 201, callerid: 201 }
    - { name: 202, callerid: 202 }
    - { name: 203, callerid: 203 }
    - { name: 204, callerid: 204 }
  notify: sip reload
